# Generated by Django 5.2.1 on 2025-05-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('url_type', models.CharField(max_length=50)),
                ('interval', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.URLField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
