# Generated by Django 5.2.1 on 2025-06-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('culture', models.CharField(max_length=10)),
                ('interval', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='ems_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMSLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('locName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='EMSData',
        ),
        migrations.AddField(
            model_name='emsimage',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.emslocality'),
        ),
    ]
