# Generated by Django 5.2.1 on 2025-06-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_emsimage_emslocality_delete_emsdata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emslocality',
            old_name='locName',
            new_name='loc_name',
        ),
        migrations.AlterUniqueTogether(
            name='emslocality',
            unique_together={('site', 'loc_name')},
        ),
        migrations.AddField(
            model_name='emslocality',
            name='last_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EMSChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('default_title', models.CharField(max_length=200)),
                ('range_group', models.CharField(max_length=100)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.emslocality')),
            ],
            options={
                'unique_together': {('locality', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='EMSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('interval', models.CharField(max_length=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.emschannel')),
            ],
        ),
        migrations.DeleteModel(
            name='EMSImage',
        ),
        migrations.RemoveField(
            model_name='emslocality',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='emslocality',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='emslocality',
            name='title',
        ),
        migrations.RemoveField(
            model_name='emslocality',
            name='url',
        ),
        migrations.AddIndex(
            model_name='emsdata',
            index=models.Index(fields=['timestamp'], name='smartapp_em_timesta_899a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='emsdata',
            index=models.Index(fields=['interval'], name='smartapp_em_interva_0a5924_idx'),
        ),
    ]
