# Generated by Django 5.1.3 on 2025-06-05 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartapp", "0003_rename_locname_emslocality_loc_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EMSImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval", models.CharField(max_length=10)),
                ("culture", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="ems_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartapp.emschannel",
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartapp.emslocality",
                    ),
                ),
            ],
        ),
    ]
