# Generated by Django 5.2.1 on 2025-06-28 07:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_rename_locname_emslocality_loc_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_type', models.CharField(choices=[('data', 'Data Callback'), ('image', 'Image Callback')], max_length=20)),
                ('site', models.CharField(max_length=100)),
                ('loc_name', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EMSImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(max_length=10)),
                ('culture', models.CharField(default='en', max_length=10)),
                ('image', models.ImageField(upload_to='ems_images/')),
                ('width', models.IntegerField(default=600)),
                ('height', models.IntegerField(default=400)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='emschannel',
            options={'ordering': ['channel_id']},
        ),
        migrations.AlterModelOptions(
            name='emslocality',
            options={'verbose_name_plural': 'EMS Localities'},
        ),
        migrations.AddField(
            model_name='emschannel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emschannel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emschannel',
            name='last_data_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emschannel',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='emsdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emsdata',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emsdata',
            name='quality_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='emslocality',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emslocality',
            name='last_callback_received',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emslocality',
            name='original_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='emslocality',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emschannel',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='smartapp.emslocality'),
        ),
        migrations.AlterField(
            model_name='emsdata',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='smartapp.emschannel'),
        ),
        migrations.AlterUniqueTogether(
            name='emsdata',
            unique_together={('channel', 'timestamp', 'interval')},
        ),
        migrations.AddIndex(
            model_name='emsdata',
            index=models.Index(fields=['channel', 'timestamp'], name='smartapp_em_channel_8e010b_idx'),
        ),
        migrations.AddField(
            model_name='emsimage',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='smartapp.emschannel'),
        ),
        migrations.AddField(
            model_name='emsimage',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='smartapp.emslocality'),
        ),
        migrations.AlterUniqueTogether(
            name='emsimage',
            unique_together={('locality', 'channel', 'interval', 'culture')},
        ),
    ]
