# Generated by Django 5.2.1 on 2025-07-03 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0004_emscallbacklog_emsimage_alter_emschannel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Relative humidity in %', null=True)),
                ('pressure', models.FloatField(blank=True, help_text='Atmospheric pressure in hPa', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in m/s', null=True)),
                ('wind_direction', models.FloatField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('rainfall', models.FloatField(blank=True, help_text='Rainfall in mm', null=True)),
                ('solar_radiation', models.FloatField(blank=True, help_text='Solar radiation in W/m²', null=True)),
                ('soil_temperature', models.FloatField(blank=True, help_text='Soil temperature in Celsius', null=True)),
                ('soil_moisture', models.FloatField(blank=True, help_text='Soil moisture in %', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='smartapp.emslocality')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['locality', '-timestamp'], name='smartapp_em_localit_ebcee7_idx'), models.Index(fields=['timestamp'], name='smartapp_em_timesta_4d41a1_idx')],
                'unique_together': {('locality', 'timestamp')},
            },
        ),
    ]
